# --- Jekyll Config --- 

# Name of website
name: Kart.xzpy
description: An SRB2 Kart server
url: "https://ebears.github.io/kart-server-site/"
remote_theme: "dracula/gh-pages"

# --- Misc ---

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# --- Plugins ---

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
#  - jekyll-paginate
#  - jekyll-sitemap
